fields:
  feeds:
    type: grid
    display: Locations
    fields:
      route:
        type: text
        width: 33
      type:
        type: select
        display: Type
        options:
          json: JSON
          atom: ATOM
        width: 33
      title:
        type: text
        instruct: Feed title
        width: 33
      collections:
        type: collections
        width: 33
      author_field:
        type: text
        width: 33
      name_fields:
        type: list
        width: 33
      custom_content:
        type: toggle
        default: false
      content:
        type: textarea
    mode: stacked
  discovery:
    type: list
